name: Build APK (Capacitor)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # ---- FRONTEND: build Vite ----
      - name: Build frontend
        working-directory: frontend
        run: |
          npm install
          npm run build

      # ---- CAPACITOR: przygotowanie w katalogu frontend/ ----
      - name: Prepare Capacitor in frontend
        working-directory: frontend
        run: |
          # pakiety potrzebne do Capacitora i Androida
          npm install --save-dev @capacitor/core @capacitor/cli @capacitor/android
          # TypeScript jest wymagany, bo config jest .ts
          npm install --save-dev typescript ts-node
          # kopiujemy nasz config do frontu
          cp ../mobile/mobile/capacitor.config.json ./capacitor.config.json
          npx cap add android
          npx cap sync android

      # ---- Toolchain Android + Java ----
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # ---- Build APK ----
      - name: Build Debug APK
        working-directory: frontend/android
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: frontend/android/app/build/outputs/apk/debug/*.apk
